apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: namespacedvalidatingtypes.app.redislabs.com
spec:
  group: app.redislabs.com
  names:
    kind: NamespacedValidatingType
    listKind: NamespacedValidatingTypeList
    plural: namespacedvalidatingtypes
    singular: namespacedvalidatingtype
  scope: Cluster
  versions:
  - name: v1alpha1
    served: true
    storage: true
  subresources:
    status: {}
