apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: namespacedvalidatingrules.app.redislabs.com
spec:
  group: app.redislabs.com
  names:
    kind: NamespacedValidatingRule
    listKind: NamespacedValidatingRuleList
    plural: namespacedvalidatingrules
    singular: namespacedvalidatingrule
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
  subresources:
    status: {}
