apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gesher
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.redislabs.com
  resources:
  - namespacedvalidatingtypes
  - namespacedvalidatingtypes/status
  - namespacedvalidatingrules
  - namespacedvalidatingrules/status
  verbs: ["*"]
