apiVersion: apps/v1
kind: Deployment
metadata:
  name: gesher
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gesher
  template:
    metadata:
      labels:
        name: gesher
    spec:
      serviceAccountName: gesher
      containers:
        - name: gesher
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - gesher
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "gesher"
