// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	v1beta1 "k8s.io/api/admissionregistration/v1beta1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyValidatingType) DeepCopyInto(out *ProxyValidatingType) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyValidatingType.
func (in *ProxyValidatingType) DeepCopy() *ProxyValidatingType {
	if in == nil {
		return nil
	}
	out := new(ProxyValidatingType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProxyValidatingType) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyValidatingTypeList) DeepCopyInto(out *ProxyValidatingTypeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProxyValidatingType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyValidatingTypeList.
func (in *ProxyValidatingTypeList) DeepCopy() *ProxyValidatingTypeList {
	if in == nil {
		return nil
	}
	out := new(ProxyValidatingTypeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProxyValidatingTypeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyValidatingTypeSpec) DeepCopyInto(out *ProxyValidatingTypeSpec) {
	*out = *in
	if in.Types != nil {
		in, out := &in.Types, &out.Types
		*out = make([]v1beta1.RuleWithOperations, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyValidatingTypeSpec.
func (in *ProxyValidatingTypeSpec) DeepCopy() *ProxyValidatingTypeSpec {
	if in == nil {
		return nil
	}
	out := new(ProxyValidatingTypeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyValidatingTypeStatus) DeepCopyInto(out *ProxyValidatingTypeStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyValidatingTypeStatus.
func (in *ProxyValidatingTypeStatus) DeepCopy() *ProxyValidatingTypeStatus {
	if in == nil {
		return nil
	}
	out := new(ProxyValidatingTypeStatus)
	in.DeepCopyInto(out)
	return out
}
